name: Angular

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: v16.14

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install dependencies
      run: |
        cd ClashRoyaleClanWarsApp
        npm install 

    - name: Build Angular app
      run: |
        cd ClashRoyaleClanWarsApp
        ng build
  
