name: Build and Test Angular App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: v16.13

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Change directory to Angular app
      run: cd ClashRoyaleClanWarsApp

    - name: LS
      run: ls

    - name: Install dependencies
      run: npm install

    - name: Build Angular app
      run: ng build

    - name: Run tests
      run: ng test
