name: Close Issue or PR on Column Move

on:
  project_card:
    types:
      - moved

jobs:
  close-item:
    runs-on: ubuntu-latest

    steps:
    - name: Check Column Name
      id: check-column
      run: echo "::set-output name=column::${{ github.event.project_card.column_name }}"

    - name: Close Issue or PR
      if: steps.check-column.outputs.column == 'Completed'
      run: |
        # Get the content ID of the card (issue or pull request)
        content_id="${{ github.event.project_card.content_id }}"
        
        # Check if the content is an issue or pull request
        is_issue_or_pr=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "https://api.github.com/repos/${{ github.repository }}/issues/$content_id" | jq '.html_url')
        
        # Determine the API URL based on whether it's an issue or pull request
        if [[ $is_issue_or_pr != "null" ]]; then
          api_url="https://api.github.com/repos/${{ github.repository }}/issues/$content_id"
        else
          api_url="https://api.github.com/repos/${{ github.repository }}/pulls/$content_id"
        fi
        
        # Close the issue or pull request using the GitHub API
        curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"state":"closed"}' \
          "$api_url"
